export const initialCholecystectomyState = {
  patientInfo: {
    name: "",
    patientId: "",
    dateOfBirth: "",
    age: "",
    sex: "",
    sexOther: "",
    weight: "",
    height: "",
    bmi: "",
    asaScore: "",
    asaNotes: "",
  },
  preoperative: {
    surgeons: [""],
    assistants: [""],
    anaesthetists: [""],
    indication: [] as string[],
    indicationOther: "",
    operationDescription: "",
    procedureUrgency: "",
    imaging: [] as string[],
    imagingOther: "",
    duration: "",
    startTime: "",
    endTime: "",
  },
  intraoperative: {
    gallbladderAppearance: [] as string[],
    gallbladderAppearanceOther: "",
    adhesionsToGallbladder: "",
  },
  procedure: {
    approach: [] as string[],
    reasonForConversion: [] as string[],
    reasonForConversionOther: "",
    subtotalCholecystectomy: "",
    subtotalReason: [] as string[],
    subtotalReasonOther: "",
    gallbladderDecompressionRequired: "",
    calotsTriangleDissected: "",
    cysticDuctIdentified: "",
    cysticArteryIdentified: "",
    twoStructuresConfirmed: "",
    cysticDuctControl: [] as string[],
    cysticDuctControlOther: "",
    cysticArteryControl: [] as string[],
    cysticArteryControlOther: "",
    gallbladderDissectedFromLiverBed: [] as string[],
    gallbladderDissectedFromLiverBedOther: "",
    bileSpillage: "",
    stonesSpillage: "",
    additionalProcedures: [] as string[],
    additionalProcedureDrainSite: "",
    additionalProceduresOther: "",
    cholangiogramFindings: [] as string[],
    cholangiogramStrictureSite: "",
    cholangiogramDilatation: "",
    cholangiogramLeakSite: "",
    cholangiogramOther: "",
    gallbladderRetrieval: [] as string[],
    gallbladderRetrievalOther: "",
    drainInsertion: "",
  },
  closure: {
    fascialClosure: "",
    skinClosureMethod: [] as string[],
    skinClosureOther: "",
    gallbladderSentForHistology: "",
    laboratoryName: "",
    intraoperativeDifficulty: [] as string[],
    intraoperativeDifficultyOther: "",
    complications: [] as string[],
    complicationsOther: "",
  },
  additionalInfo: {
    additionalInformation: "",
    postOperativeManagement: "",
    surgeonSignature: "",
    surgeonSignatureText: "",
    dateTime: "",
  },
  procedureFindings: {
    findings: "",
    additionalNotes: "",
  },
};

export const createInitialCholecystectomyState = () =>
  JSON.parse(JSON.stringify(initialCholecystectomyState));
