import { createInitialPatientInfoState } from "@/utils/patientSticker";

export const initialCholecystectomyState = {
  patientInfo: createInitialPatientInfoState(),
  preoperative: {
    surgeons: [""],
    assistants: [""],
    anaesthetists: [""],
    indication: [] as string[],
    indicationOther: "",
    operationDescription: "",
    procedureUrgency: "",
    imaging: [] as string[],
    imagingOther: "",
    duration: "",
    startTime: "",
    endTime: "",
  },
  intraoperative: {
    gallbladderAppearance: [] as string[],
    gallbladderAppearanceOther: "",
    adhesionsToGallbladder: "",
    stonesPresent: "",
    typeOfStones: "",
    typeOfStonesOther: "",
    sizeOfStones: "",
  },
  procedure: {
    approach: [] as string[],
    reasonForConversion: [] as string[],
    reasonForConversionOther: "",
    numberOfPortsInserted: "",
    subtotalCholecystectomy: "",
    subtotalReason: [] as string[],
    subtotalReasonOther: "",
    adhesiolysis: "",
    extentOfCholecystectomy: "",
    extentOfCholecystectomyOther: "",
    methodOfSubtotalControl: [] as string[],
    methodOfSubtotalControlOther: "",
    gallbladderDecompressionRequired: "",
    criticalViewSafetyConfirmation: [] as string[],
    criticalViewSafetyConfirmationOther: "",
    calotsTriangleDissected: "",
    cysticDuctIdentified: "",
    cysticArteryIdentified: "",
    twoStructuresConfirmed: "",
    cysticDuctControl: [] as string[],
    cysticDuctControlOther: "",
    cysticArteryControl: [] as string[],
    cysticArteryControlOther: "",
    gallbladderDissectedFromLiverBed: [] as string[],
    gallbladderDissectedFromLiverBedOther: "",
    hemostasis: [] as string[],
    hemostasisOther: "",
    bileSpillage: "",
    stonesSpillage: "",
    additionalProcedures: [] as string[],
    additionalProcedureDrainSite: "",
    additionalProceduresOther: "",
    cholangiogramFindings: [] as string[],
    cholangiogramStrictureSite: "",
    cholangiogramDilatation: "",
    cholangiogramLeakSite: "",
    cholangiogramOther: "",
    gallbladderRetrieval: [] as string[],
    gallbladderRetrievalOther: "",
    useOfSpecimenBag: "",
    peritonealLavage: [] as string[],
    peritonealLavageOther: "",
    drainInsertion: "",
    drainType: [] as string[],
    drainTypeOther: "",
    intraPeritonealPlacement: [] as string[],
    intraPeritonealPlacementOther: "",
    drainExitSite: [] as string[],
    drainExitSiteOther: "",
  },
  closure: {
    fascialClosure: "",
    fascialClosureSites: [] as string[],
    fascialSutureMaterial: [] as string[],
    fascialSutureMaterialOther: "",
    skinClosure: "",
    skinClosureMethod: [] as string[],
    skinClosureOther: "",
    useOfSpecimenBag: "",
    gallbladderSentForHistology: "",
    laboratoryName: "",
    intraoperativeDifficulty: [] as string[],
    intraoperativeDifficultyOther: "",
    complications: [] as string[],
    complicationsOther: "",
  },
  additionalInfo: {
    additionalInformation: "",
    postOperativeManagement: "",
    surgeonSignature: "",
    surgeonSignatureText: "",
    dateTime: "",
  },
  procedureFindings: {
    findings: "",
    additionalNotes: "",
  },
};

export const createInitialCholecystectomyState = () =>
  JSON.parse(JSON.stringify(initialCholecystectomyState));
