import { createInitialPatientInfoState } from "@/utils/patientSticker";
import {
  createDefaultClinicianList,
  DEFAULT_CLINICIAN_NAME,
} from "@/utils/clinicianDefaults";

export const initialColonoscopyState = {
  patientInfo: createInitialPatientInfoState(),
  preoperative: {
    endoscopists: createDefaultClinicianList(),
    assistants: [""],
    anaesthetists: [""],
    startTime: "",
    caecalIntubationTime: "",
    withdrawalStartTime: "",
    endTime: "",
    duration: "",
    withdrawalDuration: "",
    indications: [] as string[],
    indicationOther: "",
    signsSymptoms: [] as string[],
    signsSymptomsOther: "",
    procedureUrgency: [] as string[],
    preoperativeImaging: [] as string[],
    preoperativeImagingOther: "",
    sedationist: "",
    sedationistOther: "",
    sedationTypes: [] as string[],
    sedationTypeOther: "",
    medicationsUsed: [] as string[],
    medications: {
      midazolamDose: "",
      fentanylDose: "",
      propofolDose: "",
      otherMedication: "",
    },
    monitoring: [] as string[],
    monitoringOther: "",
    sedationLevel: "",
  },
  bowelPreparation: {
    prepType: [] as string[],
    prepTypeOther: "",
    overallAssessment: "",
    bbpsRightColon: "",
    bbpsTransverseColon: "",
    bbpsLeftColon: "",
    totalBbps: "",
  },
  procedureDetails: {
    procedures: [] as string[],
    procedureOther: "",
    depthOfExamination: [] as string[],
    caecalLandmarks: [] as string[],
    caecalLandmarksOther: "",
    reasonsCaecumNotReached: [] as string[],
    reasonsCaecumNotReachedOther: "",
    difficulty: "",
  },
  findingsSummary: {
    findings: [] as string[],
    findingOther: "",
    sitesOfAbnormality: [] as string[],
    siteOther: "",
    descriptionOfFindings: "",
  },
  haemorrhoids: {
    grades: [] as string[],
    grade: "",
    internalExternal: "",
    bleedingStatus: [] as string[],
  },
  inflammation: {
    description: [] as string[],
    descriptionOther: "",
    severity: "",
    ulcerBurden: "",
    ulcerFeatures: [] as string[],
    ulcerFeaturesOther: "",
    endoscopicImpression: [] as string[],
    impressionOther: "",
  },
  stricture: {
    number: "",
    multipleNumber: "",
    length: "",
    severityOfNarrowing: [] as string[],
    traversability: [] as string[],
    morphology: [] as string[],
    morphologyOther: "",
    endoscopicImpression: [] as string[],
    impressionOther: "",
  },
  polyps: {
    number: "",
    size: [] as string[],
    largestDiameterLength: "",
    largestDiameterWidth: "",
    rangeFrom: "",
    rangeTo: "",
    morphology: [] as string[],
    morphologyOther: "",
  },
  tumour: {
    length: "",
    circumferentialInvolvement: [] as string[],
    lumenNarrowing: [] as string[],
    endoscopicImpression: [] as string[],
  },
  diverticula: {
    number: "",
    size: "",
    distributionPattern: [] as string[],
    morphology: [] as string[],
    morphologyOther: "",
  },
  avMalformation: {
    number: "",
    size: "",
    morphology: [] as string[],
    colorAppearance: [] as string[],
    bleedingStatus: [] as string[],
    distributionPattern: [] as string[],
    burden: "",
    bleedingRisk: "",
  },
  radiationProctitis: {
    extentFromAnalVerge: "",
    distribution: [] as string[],
    severity: "",
    mucosalFindings: [] as string[],
    mucosalFindingsOther: "",
  },
  ulcer: {
    number: "",
    approximateNumberIfMultiple: "",
    distribution: [] as string[],
    largestDiameterLength: "",
    largestDiameterWidth: "",
    rangeFrom: "",
    rangeTo: "",
    shape: [] as string[],
    depth: [] as string[],
    edges: [] as string[],
    base: [] as string[],
    orientation: [] as string[],
    bleedingStigmata: [] as string[],
    surroundingMucosa: [] as string[],
    surroundingMucosaOther: "",
    associatedFindings: [] as string[],
    associatedFindingsOther: "",
    suspectedEtiology: [] as string[],
    ibdType: [] as string[],
    infectiveEtiology: [] as string[],
    etiologyOther: "",
  },
  interventions: {
    interventions: [] as string[],
    other: "",
  },
  diagnosis: {
    diagnoses: [] as string[],
    diagnosisOther: "",
  },
  additionalInfo: {
    specimenSentForPathology: "",
    otherSpecimensTaken: "",
    otherSpecimensTakenDetails: "",
    laboratorySentTo: "",
    conclusion: "",
    followUpOptions: [] as string[],
    followUpOther: "",
    additionalNotes: "",
    management: "",
    postOperativeManagement: "",
    endoscopistName: DEFAULT_CLINICIAN_NAME,
    surgeonSignature: "",
    surgeonSignatureText: DEFAULT_CLINICIAN_NAME,
    dateTime: "",
  },
  diagram: {
    findings: [] as any[],
    canvasImageData: "",
  },
};

export const createInitialColonoscopyState = () =>
  JSON.parse(JSON.stringify(initialColonoscopyState));
