import { createInitialPatientInfoState } from "@/utils/patientSticker";

export const initialGastroscopyState = {
  patientInfo: createInitialPatientInfoState(),
  preoperative: {
    endoscopists: [""],
    surgeons: [""],
    anaesthetists: [""],
    indications: [] as string[],
    indicationOther: "",
    signsSymptoms: [] as string[],
    signsSymptomsOther: "",
    extentOfExamination: [] as string[],
    sedationist: "",
    sedationistOther: "",
    sedationTypes: [] as string[],
    medications: {
      midazolamDose: "",
      fentanylDose: "",
      propofolDose: "",
      otherMedication: "",
    },
    monitoring: [] as string[],
    monitoringOther: "",
    sedationLevel: "",
  },
  pharynxLarynx: {
    pharynxStatus: "",
    pharynxAbnormality: "",
    vocalCordsStatus: "",
    vocalCordsAbnormality: "",
  },
  oesophagus: {
    findings: [] as string[],
    barrettType: "",
    barrettLength: "",
    candidaSeverity: "",
    ulcerAppearance: "",
    oesophagitisGrade: "",
    hiatusHerniaGrade: "",
    hiatusHerniaLength: "",
    kaposiMultiplicity: "",
    malloryWeissBleeding: "",
    webLocation: [] as string[],
    strictureType: "",
    malignancyLocation: [] as string[],
    malignancyLength: "",
    diverticulumLocation: [] as string[],
    varicesGrade: "",
    other: "",
  },
  stomach: {
    findings: [] as string[],
    ulcerCount: "",
    ulcerFeatures: "",
    forrestClassification: [] as string[],
    massMorphology: [] as string[],
    erosionCount: "",
    erosionAssociatedWithGastritis: "",
    gastritisType: [] as string[],
    gastritisSeverity: "",
    gistMucosa: "",
    kaposiPattern: [] as string[],
    gavePattern: [] as string[],
    varicesNumber: "",
    varicesClassification: [] as string[],
    polypNumber: "",
    polypSize: [] as string[],
    portalGastropathySeverity: "",
    portalGastropathyMucosa: [] as string[],
    strictureMucosa: [] as string[],
    siteOfLesion: [] as string[],
    other: "",
  },
  duodenum: {
    findings: [] as string[],
    duodenitisSeverity: "",
    erosionsPresent: "",
    ulcerCount: "",
    ulcerFeatures: "",
    forrestClassification: [] as string[],
    polypCount: "",
    polypSize: [] as string[],
    tumourMorphology: [] as string[],
    strictureMucosa: [] as string[],
    siteOfLesion: [] as string[],
    other: "",
  },
  interventions: {
    interventions: [] as string[],
    dilatationTypes: [] as string[],
    maxDilatationMm: "",
    bandingCount: "",
    clipCount: "",
    stentTypes: [] as string[],
    stentLengthCm: "",
    stentDiameterMm: "",
    injectionAgent: "",
    other: "",
  },
  diagnosis: {
    diagnoses: [] as string[],
    diagnosisOther: "",
  },
  additionalInfo: {
    comments: "",
    conclusion: "",
    management: "",
    endoscopistName: "",
    surgeonSignature: "",
    surgeonSignatureText: "",
    dateTime: "",
  },
  diagram: {
    findings: [] as any[],
    canvasImageData: "",
  },
};

export const createInitialGastroscopyState = () =>
  JSON.parse(JSON.stringify(initialGastroscopyState));
