import { createInitialPatientInfoState } from "@/utils/patientSticker";
import { createDefaultClinicianList, DEFAULT_CLINICIAN_NAME } from "@/utils/clinicianDefaults";

export const initialGastroscopyState = {
  patientInfo: createInitialPatientInfoState(),
  preoperative: {
    endoscopists: createDefaultClinicianList(),
    surgeons: createDefaultClinicianList(),
    anaesthetists: [""],
    procedureUrgency: "",
    preoperativeImaging: [] as string[],
    preoperativeImagingOther: "",
    startTime: "",
    endTime: "",
    duration: "",
    indications: [] as string[],
    indicationOther: "",
    signsSymptoms: [] as string[],
    signsSymptomsOther: "",
    extentOfExamination: [] as string[],
    sedationist: "",
    sedationistOther: "",
    sedationTypes: [] as string[],
    medications: {
      midazolamDose: "",
      fentanylDose: "",
      propofolDose: "",
      otherMedication: "",
    },
    monitoring: [] as string[],
    monitoringOther: "",
    sedationLevel: "",
  },
  pharynxLarynx: {
    pharynxStatus: "",
    pharynxAbnormality: "",
    vocalCordsStatus: "",
    vocalCordsAbnormality: "",
  },
  oesophagus: {
    findings: [] as string[],
    barrettType: [] as string[],
    barrettLength: "",
    candidaSeverity: [] as string[],
    ulcerAppearance: [] as string[],
    oesophagitisGrade: [] as string[],
    hiatusHerniaGrade: [] as string[],
    hiatusHerniaLength: "",
    kaposiMultiplicity: [] as string[],
    malloryWeissBleeding: [] as string[],
    webLocation: [] as string[],
    strictureType: [] as string[],
    malignancyLocation: [] as string[],
    malignancyLength: "",
    diverticulumLocation: [] as string[],
    varicesGrade: [] as string[],
    other: "",
  },
  stomach: {
    findings: [] as string[],
    ulcerSelections: [] as string[],
    forrestClassification: [] as string[],
    massMorphology: [] as string[],
    erosionSelections: [] as string[],
    gastritisType: [] as string[],
    gastritisTypeOther: "",
    gastritisSeverity: [] as string[],
    gistMucosa: [] as string[],
    kaposiPattern: [] as string[],
    gavePattern: [] as string[],
    varicesNumber: [] as string[],
    varicesClassification: [] as string[],
    polypNumber: [] as string[],
    polypSize: [] as string[],
    portalGastropathySeverity: [] as string[],
    portalGastropathyMucosa: [] as string[],
    strictureMucosa: [] as string[],
    other: "",
  },
  duodenum: {
    findings: [] as string[],
    duodenitisSeverity: [] as string[],
    duodenitisWithErosions: [] as string[],
    ulcerSelections: [] as string[],
    forrestClassification: [] as string[],
    polypNumber: [] as string[],
    polypSize: [] as string[],
    tumourMorphology: [] as string[],
    strictureMucosa: [] as string[],
    other: "",
  },
  interventions: {
    interventions: [] as string[],
    dilatationTypes: [] as string[],
    maxDilatationMm: "",
    bandingCount: "",
    clipCount: "",
    stentTypes: [] as string[],
    stentLengthCm: "",
    stentDiameterMm: "",
    injectionAgent: "",
    other: "",
  },
  diagnosis: {
    diagnoses: [] as string[],
    diagnosisOther: "",
  },
  additionalInfo: {
    specimenSentForPathology: "",
    laboratorySentTo: "",
    otherSpecimensTaken: "",
    otherSpecimensDetails: "",
    comments: "",
    conclusion: "",
    management: "",
    followUp: [] as string[],
    followUpOther: "",
    additionalNotes: "",
    postOperativeManagement: "",
    endoscopistName: DEFAULT_CLINICIAN_NAME,
    surgeonSignature: "",
    surgeonSignatureText: DEFAULT_CLINICIAN_NAME,
    dateTime: "",
  },
  diagram: {
    findings: [] as any[],
    drawingImageData: "",
    textAnnotations: [] as any[],
    canvasImageData: "",
  },
};

export const createInitialGastroscopyState = () =>
  JSON.parse(JSON.stringify(initialGastroscopyState));
