import { createInitialPatientInfoState } from "@/utils/patientSticker";
import { DEFAULT_CLINICIAN_NAME } from "@/utils/clinicianDefaults";

export const initialInguinalHerniaState = {
  patientInfo: createInitialPatientInfoState(),
  preoperative: {
    surgeon: "",
    assistant: "",
    anaesthetist: "",
    preoperativeImaging: [] as string[],
    preoperativeImagingOther: "",
    startTime: "",
    endTime: "",
    duration: "",
    operationDescription: "",
    indication: [] as string[],
    indicationOther: "",
    urgency: "",
  },
  operativeFindings: {
    type: [] as string[],
    typeOther: "",
    side: "",
    sizeOfDefect: "",
    contents: [] as string[],
    contentsOther: "",
    posteriorWall: "",
    additionalPathology: "",
  },
  procedure: {
    description: "",
    technique: [] as string[],
    techniqueOther: "",
    approach: "",
    approachOther: "",
    reasonForConversion: [] as string[],
    reasonForConversionOther: "",
    trocarNumber: "",
    incisionUsed: [] as string[],
    incisionOther: "",
    incisionLength: "",
    externalObliqueAponeurosisIncised: "",
    cordStructures: [] as string[],
    nervesIdentified: [] as string[],
    ilioinguinalPreserved: "",
    iliohypogastricPreserved: "",
    genitalBranchPreserved: "",
    sacManagement: [] as string[],
    deepRingReconstruction: "",
    repairTechnique: [] as string[],
    tissueReconstruction: [] as string[],
    tissueReconstructionOther: "",
    sutureMaterial: "",
    sutureMethod: "",
    meshInserted: "",
    meshSizeLength: "",
    meshSizeWidth: "",
    meshPositioning: [] as string[],
    meshPositioningOther: "",
    fixation: [] as string[],
    fixationPoints: [] as string[],
    fixationPointsOther: "",
    laparoscopicApproach: "",
    preperitonealDevelopment: [] as string[],
    preperitonealDevelopmentOther: "",
    landmarks: [] as string[],
    laparoscopicSacManagement: [] as string[],
    laparoscopicMeshUsed: "",
    laparoscopicMeshSizeLength: "",
    laparoscopicMeshSizeWidth: "",
    laparoscopicFixation: [] as string[],
    laparoscopicFixationSites: [] as string[],
    laparoscopicFixationSitesOther: "",
    peritoneumClosure: "",
  },
  closure: {
    externalObliqueClosure: "",
    subcutaneousTissueClosure: "",
    skinClosureOpen: [] as string[],
    localAnaestheticOpen: "",
    fascialClosurePorts: "",
    skinClosureLaparoscopic: [] as string[],
    localAnaestheticLaparoscopic: "",
  },
  complications: {
    complications: [] as string[],
    complicationOther: "",
  },
  additionalInfo: {
    additionalNotes: "",
    postOperativeManagement: "",
    surgeonSignature: "",
    surgeonSignatureText: DEFAULT_CLINICIAN_NAME,
    dateTime: "",
  },
  procedureFindings: {
    findings: "",
    additionalNotes: "",
  },
};

export const createInitialInguinalHerniaState = () =>
  JSON.parse(JSON.stringify(initialInguinalHerniaState));
