import { createInitialPatientInfoState } from "@/utils/patientSticker";
import { createDefaultClinicianList, DEFAULT_CLINICIAN_NAME } from "@/utils/clinicianDefaults";
import {
  createInitialPeriAnalDiagramMarkings,
  DEFAULT_PERI_ANAL_DIAGRAM_VARIANT,
} from "@/utils/periAnalDiagramConfig";

export const initialPeriAnalState = {
  patientInfo: createInitialPatientInfoState(),
  preoperative: {
    surgeons: createDefaultClinicianList(),
    assistants: [""],
    anaesthetists: [""],
    indication: "",
    operationDescription: "",
    procedureUrgency: "",
    imaging: [] as string[],
    imagingOther: "",
    duration: "",
    startTime: "",
    endTime: "",
    positionInTheatre: "",
    positionOther: "",
  },
  findings: {
    selectedFindings: [] as string[],
    otherFindingText: "",
    perianalAbscess: {
      descriptionOfFindings: "",
      location: [] as string[],
      locationOther: "",
      sizeLength: "",
      sizeWidth: "",
      siteOfAbscess: [] as string[],
      siteOfAbscessOther: "",
      fluctance: "",
      overlyingSkin: [] as string[],
      overlyingSkinOther: "",
      associatedInternalOpening: "",
      positionOfInternalOpening: "",
      procedurePerformed: [] as string[],
      procedurePerformedOther: "",
      pusDrainedVolume: "",
      irrigationPerformed: "",
      woundControl: [] as string[],
      woundControlOther: "",
    },
    perianalFistula: {
      descriptionOfFindings: "",
      classification: [] as string[],
      numberOfExternalOpenings: "",
      externalOpeningClockPosition: "",
      externalOpeningDistanceFromAnalVerge: "",
      numberOfInternalOpenings: "",
      internalOpeningClockPosition: "",
      internalOpeningNoneFound: "",
      positionOfInternalOpenings: [] as string[],
      positionOfInternalOpeningsOther: "",
      associatedAbscessCavity: "",
      sphincterInvolvement: "",
      horseshoeExtension: "",
      secondaryTracts: "",
      procedurePerformed: [] as string[],
      procedurePerformedOther: "",
      methodOfIdentifyingInternalOpening: [] as string[],
      methodOfIdentifyingInternalOpeningOther: "",
      fistulotomyDetails: {
        tractLaidOpen: "",
        percentageOfSphincterDivided: "",
        curettageOfTract: "",
        marsupialisationPerformed: "",
        lengthOfTract: "",
      },
      setonProcedureDetails: {
        typeOfSeton: "",
        materialUsed: [] as string[],
        materialUsedOther: "",
        numberOfSetonsPlaced: "",
        plannedDuration: "",
      },
      liftProcedureDetails: {
        intersphinctericPlaneIdentified: "",
        dissectionMethod: [] as string[],
        surroundingFibrosis: "",
        tractDivided: "",
        closureOfInternalOpening: "",
        closureOfExternalTract: "",
        externalTractManagement: [] as string[],
        externalTractManagementOther: "",
        advancementFlapAdded: "",
        biologicAdjunctUsed: "",
      },
      advancementFlapDetails: {
        flapType: "",
        lengthOfFlap: "",
        internalOpeningExcised: "",
        flapVascularityAdequate: "",
        externalTractManagement: [] as string[],
        externalTractManagementOther: "",
      },
      plugGlueDetails: {
        whichWasUsed: [] as string[],
        plugType: [] as string[],
        plugTypeOther: "",
        glueType: [] as string[],
        tractCurettagePerformed: "",
        irrigation: [] as string[],
        irrigationOther: "",
        insertionDirection: [] as string[],
        internalOpeningClosure: "",
      },
      fistulectomyDetails: {
        extentOfTractExcision: "",
        closureOfInternalOpening: "",
      },
    },
    fissureInAno: {
      descriptionOfFindings: "",
      location: [] as string[],
      locationOther: "",
      heightFromAnalVerge: "",
      sentinelPile: "",
      hypertrophiedPapilla: "",
      sphincterHypertonicity: "",
      procedurePerformed: [] as string[],
      procedurePerformedOther: "",
      lateralInternalSphincterotomyDetails: {
        sideOfLateralInternalSphincterotomy: "",
        extentOfSphincterDivided: "",
        skinTagExcision: "",
      },
      botoxInjectionDetails: {
        botoxDoseInjection: "",
        botoxDoseOther: "",
        muscleOfInjection: [] as string[],
        muscleOfInjectionOther: "",
        numberOfSitesOfInjection: "",
        sitesOfInjection: [] as string[],
        sitesOfInjectionOther: "",
      },
      advancementFlapDetails: {
        flapType: "",
        lengthOfFlap: "",
        flapVascularityAdequate: "",
      },
    },
    haemorrhoids: {
      descriptionOfFindings: "",
      type: [] as string[],
      internalHaemorrhoidGrade: "",
      columnsInvolved: [] as string[],
      columnsInvolvedOther: "",
      complications: [] as string[],
      complicationsOther: "",
      procedurePerformed: [] as string[],
      procedurePerformedOther: "",
      numberOfColumnsTreated: "",
      energyDeviceUsedForHaemorrhoidectomy: "",
      mucosalBridgesPreserved: "",
      haemostasisAchieved: "",
      analPackInserted: "",
    },
    warts: {
      descriptionOfFindings: "",
      distributionOfWarts: [] as string[],
      distributionOfWartsOther: "",
      sizeOfLesions: "",
      morphology: [] as string[],
      excisionMethod: [] as string[],
      excisionMethodOther: "",
      depthOfExcision: [] as string[],
      haemostasisAchieved: "",
    },
    hidradenitisSuppurativa: {
      descriptionOfFindings: "",
      sitesInvolved: [] as string[],
      laterality: "",
      nodulesPresent: "",
      abscessesPresent: "",
      sinusTractsPresent: "",
      activeDischarge: [] as string[],
      surroundingSkinCondition: [] as string[],
      depthOfDisease: [] as string[],
      depthOfDiseaseOther: "",
      operativeProcedurePerformed: [] as string[],
      operativeProcedurePerformedOther: "",
      extentOfExcision: "",
      haemostasisAchieved: "",
    },
    necrotisingFasciitis: {
      involvedAreas: [] as string[],
      depthOfDisease: [] as string[],
      depthOfDiseaseOther: "",
      foulOdour: "",
      etiologyIdentified: [] as string[],
      areasDebrided: [] as string[],
      areasDebridedOther: "",
      depthOfDebridement: [] as string[],
      depthOfDebridementOther: "",
      testicularInvolvement: "",
      orchidectomySide: "",
      diversionStomaRequired: "",
      plannedRedeBridement: "",
    },
    massLesion: {
      descriptionOfFindings: "",
      locationOfMass: [] as string[],
      sizeLength: "",
      sizeWidth: "",
      numberOfLesions: "",
      surfaceChanges: [] as string[],
      surfaceChangesOther: "",
      consistency: [] as string[],
      consistencyOther: "",
      fixationToDeeperStructures: "",
      sphincterTone: "",
      mostLikelyDiagnosis: [] as string[],
      mostLikelyDiagnosisOther: "",
      diagnosticProcedurePerformed: [] as string[],
      diagnosticProcedurePerformedOther: "",
    },
  },
  woundManagement: {
    irrigationSolution: [] as string[],
    irrigationSolutionOther: "",
    woundClosure: "",
    dressingApplied: [] as string[],
    dressingAppliedOther: "",
    analPackInserted: "",
  },
  complications: {
    intraoperativeComplications: [] as string[],
    intraoperativeComplicationsOther: "",
  },
  postOperativePlan: {
    analgesia: "",
    antibiotics: "",
    sitzBaths: "",
    packingRemovalTime: "",
    planForFurtherSurgery: "",
  },
  specimen: {
    sentForHistology: "",
    histologyLaboratorySentTo: "",
    sentForMicrobiology: "",
    microbiologyLaboratorySentTo: "",
  },
  additionalInfo: {
    additionalInformation: "",
    postOperativeManagement: "",
    surgeonSignature: "",
    surgeonSignatureText: DEFAULT_CLINICIAN_NAME,
    dateTime: "",
  },
  procedureFindings: {
    findings: "",
    additionalNotes: "",
    activeDiagramVariant: DEFAULT_PERI_ANAL_DIAGRAM_VARIANT,
    diagramMarkingsByVariant: createInitialPeriAnalDiagramMarkings(),
  },
};

export const createInitialPeriAnalState = () =>
  JSON.parse(JSON.stringify(initialPeriAnalState));
