import { createInitialPatientInfoState } from "@/utils/patientSticker";
import { createDefaultClinicianList, DEFAULT_CLINICIAN_NAME } from "@/utils/clinicianDefaults";

export const initialSmallBowelSurgeryState = {
  patientInfo: createInitialPatientInfoState(),
  preoperative: {
    surgeons: createDefaultClinicianList(),
    assistants: [""],
    anaesthetists: [""],
    indication: "",
    operationDescription: "",
    procedureUrgency: "",
    imaging: [] as string[],
    imagingOther: "",
    duration: "",
    startTime: "",
    endTime: "",
  },
  operativeFindings: {
    pathology: [] as string[],
    pathologyOther: "",
    distanceFromDjFlexure: "",
    distanceFromIleocecalValve: "",
    diseasedSegmentLength: "",
    bowelViability: "",
    mesentericInvolvement: "",
    lymphNodes: "",
    contamination: "",
    adhesions: "",
    description: "",
  },
  procedure: {
    approach: [] as string[],
    reasonForConversion: [] as string[],
    reasonForConversionOther: "",
    operationDone: "",
    procedurePerformed: [] as string[],
    procedurePerformedOther: "",
    lengthResected: "",
    margins: [] as string[],
    vascularControl: [] as string[],
    vascularControlOther: "",
    adhesiolysis: "",
    peritonealLavage: "",
    peritonealLavageVolume: "",
  },
  reconstruction: {
    reconstructionType: [] as string[],
    reconstructionOther: "",
    anastomosisDetails: {
      site: "",
      configuration: "",
      configurationOther: "",
      technique: "",
      sutureMaterial: [] as string[],
      sutureMaterialOther: "",
      linearStaplerSize: [] as string[],
      linearStaplerSizeOther: "",
      circularStaplerSize: [] as string[],
      circularStaplerSizeOther: "",
    },
    stomaDetails: {
      ileostomyType: "",
      ileostomyTypeOther: "",
      location: "",
      locationOther: "",
      eversion: "",
      maturationSite: "",
      materialUsed: [] as string[],
      materialUsedOther: "",
    },
  },
  operativeEvents: {
    specimen: [] as string[],
    specimenOther: "",
    specimenSentToLaboratory: "",
    specifyLaboratorySentTo: "",
    pointsOfDifficulty: [] as string[],
    pointsOfDifficultyOther: "",
    intraoperativeEvents: [] as string[],
    intraoperativeEventsOther: "",
    woundProtector: "",
    drainInsertion: "",
    drainType: [] as string[],
    drainTypeOther: "",
    intraPeritonealPlacement: [] as string[],
    intraPeritonealPlacementOther: "",
    drainExitSite: [] as string[],
    drainExitSiteOther: "",
  },
  closure: {
    fascialClosure: [] as string[],
    fascialClosureOther: "",
    fascialSutureMaterial: [] as string[],
    fascialSutureMaterialOther: "",
    skinClosure: [] as string[],
    skinClosureOther: "",
    skinClosureMaterial: [] as string[],
    skinClosureMaterialOther: "",
  },
  additionalInfo: {
    additionalInformation: "",
    postOperativeManagement: "",
    surgeonSignature: "",
    surgeonSignatureText: DEFAULT_CLINICIAN_NAME,
    dateTime: "",
  },
  procedureFindings: {
    findings: "",
    additionalNotes: "",
  },
};

export const createInitialSmallBowelSurgeryState = () =>
  JSON.parse(JSON.stringify(initialSmallBowelSurgeryState));
